### ISSUE TITLE
Support multiple sections

### ISSUE THREAD

**Issue by leslie-qiwa** [martialblog/cheatsheet#5]
Thanks for making this great tools! Command line tool is exactly what I like.

To ease organize different commands, sometimes, people likes to use separated sections. So can we add this support. Such as I probably want 2 separated sections on GIT. One is for standard workflow, 2nd is command for folk workflow.

**Comment by martialblog** [comment]
Hey, glad to hear you like it. 
Thanks for the input, I meant to refactor this thing a while ago. Any help is welcome.

**Comment by martialblog** [comment]
I've added the possibility to add sections here: 

https://github.com/martialblog/cheatsheet/tree/sections

The output would be:

```
COMMON
Simple example             example foobar
Example with parameter     example foo <PARAMETER>
WORKFLOW
Example in another section example barfoo
```

Any feedback? Is that what you had in mind?

**Comment by martialblog** [comment]
I'm gonna merge that

**Comment by leslie-qiwa** [comment]
is it in master now? seems like not work.
actually what I want is more than that. I hope some section layout like this one https://vim.rtorr.com. For now, the workaround is to create separate cheat files.

**Comment by martialblog** [comment]
@leslie-qiwa have you pulled the latest version? Works fine here and in the tests

**Comment by leslie-qiwa** [comment]
I thought the section name needn't be included by '[]'. it turns out I'm wrong. If I name it like [section-name], it works. Thanks for the excellent work again!

**Comment by martialblog** [comment]
Let's add an option to turn it off and on
